name: Python Code Checks and Tests

on:
  push:
    branches:
      - main  

jobs:
  checks-and-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10  

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install black flake8 isort
          pip install .

      - name: Run code formatting checks
        run: |
          black --check .
          flake8

      - name: Run import sorting check
        run: |
          isort --check-only .

      - name: Run tests
        run: |
          pytest
